name = "pricing-sync-worker"
main = "src/index.js"
compatibility_date = "2026-05-09"

[triggers]
crons = [ "0 0 * * *" ] # Run once every night at midnight

[vars]
SUPABASE_URL = "https://pbazjkkfzyovldltwrkd.supabase.co"
SUPABASE_ANON_KEY = "sb_publishable_-7jL1RyGTKvOiSmN5IUK_Q_OCy4eGcZ"
ASTRO_BUILD_WEBHOOK = "worker-sync-trigger"